DATA:
  name: "3Dcubes64"
  img_size: 64
  num_classes: 1
  img_channels: 1
  num_dims: 3
PRE:
  apply_rflip: False
MODEL:
  z_dim: 8
  g_conv_dim: 32
  d_conv_dim: 32
LOSS:
  adv_loss: "wasserstein"
  apply_gp: True
  gp_lambda: 10.0
OPTIMIZATION:
  batch_size: 32
  total_steps: 30000
  g_lr: 0.0001
  d_lr: 0.0004
  beta1: 0.0
  beta2: 0.999
  d_updates_per_step: 1
