DATA:
  name: "gpm"
  img_size: 256
  num_classes: 1
  img_channels: 3
PRE:
  apply_rflip: True
MODEL:
  z_dim: 16
  g_conv_dim: 2
  d_conv_dim: 2
LOSS:
  adv_loss: "wasserstein"
  apply_gp: True
  gp_lambda: 10.0
OPTIMIZATION:
  batch_size: 768
  total_steps: 30000
  g_lr: 0.0002
  d_lr: 0.0002
  beta1: 0.5
  beta2: 0.999
  d_updates_per_step: 1
