DATA:
  name: "gpm"
  img_size: 32
  num_classes: 1
  img_channels: 1
MODEL:
  backbone: "big_resnet"
  g_cond_mtd: "cBN"
  d_cond_mtd: "PD"
  z_dim: 64
  g_shared_dim: 8
  apply_g_ema: True
  g_ema_decay: 0.9999
  g_ema_start: 100
LOSS:
  adv_loss: "hinge"
OPTIMIZATION:
  batch_size: 256
  g_lr: 0.0001
  d_lr: 0.0004
  beta1: 0.0
  beta2: 0.999
  d_updates_per_step: 1
