DATA:
  name: "gpm"
  img_size: 32
  num_classes: 1
  img_channels: 1
MODEL:
  z_dim: 16
  g_conv_dim: 16
  d_conv_dim: 16
LOSS:
  adv_loss: "wasserstein"
  apply_gp: True
  gp_lambda: 10.0
OPTIMIZATION:
  batch_size: 2048
  g_lr: 0.0001
  d_lr: 0.0004
  beta1: 0.0
  beta2: 0.999
  d_updates_per_step: 5
